### ISSUE TITLE
TODO Überblick (bitte fehlende Punkte in Auflistung ergänzen)

### ISSUE THREAD

**Issue by d0mmi** [project-redhead/redhead#47]
1. Bis Donnerstag

- [ ] Kurzerklärung auf Startseite (Allgemeine Anforderung)
- [ ] Hilfeseiten/Anleitung (Allgemeine Anforderung)
- [ ] Impressum (Allgemeine Anforderung)
- [ ] Transactions Seite
- [ ] Sidebar
- [ ] ...
2. Bis Abgabe
- [ ] Mensa essen auf Startseite / eigene Seite
- [ ] ...
